swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: " SWAGGER IMAGES CLASSIFICATION"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: ""
schemes:
  - "http"
paths:
  /uploads:
    post:
      summary: "Add a new images to the database"
      description: "Upload new folder containing all type of document-image"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true

      responses:
        201:
          description: "Images added"
  /invoices:
    get:
      summary: "Return an array of invoice type"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/invoice"

  /budgets:
    get:
      summary: "Return a set of budgets files"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/budget"

  /specifications:
    get:
      summary: "Return a set of specs files"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/specification"

  /forms:
    get:
      summary: "Return a set of forms files"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/form"

  /unlabeled:
    get:
      summary: "All unclassified documents are set in unlabeled class"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/unlabeled"

  /handwritten:
    get:
      summary: "Return a set of budgets files"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/handwritten"

definitions:
  invoice:
    type: "object"
    properties:
      name:
        type: "string"
        description: "filename"
      url:
        type: "string"
        description: "Url for download file"
      date:
        type: "string"
        description: "Date of uploading file / entrance in the system"
        format: "date-time"
      tva:
        type: "boolean"
        description: "True if TVA exist on the invoice"
      siren:
        type: "boolean"
        description: "True if SIREN number exist in open source database"
      adresse:
        type: "boolean"
        description: "True if adress is conform to open source database"
      company_name:
        type: "string"
      score:
        type: "number"
        description: "Score of probability to fraud risk (between 0 - 100) "
  form:
    type: "object"
    properties:
      name:
        type: "string"
        description: "filename"
      url:
        type: "string"
        description: "Url to download file"

  budget:
    type: "object"
    properties:
      name:
        type: "string"
        description: "filename"
      url:
        type: "string"
        description: "Url to download file"

  unlabeled:
    type: "object"
    properties:
      name:
        type: "string"
        description: "filename"
      url:
        type: "string"
        description: "Url to download file"

  specification:
    type: "object"
    properties:
      name:
        type: "string"
        description: "filename"
      url:
        type: "string"
        description: "Url to download file"

  handwritten:
    type: "object"
    properties:
      name:
        type: "string"
        description: "filename"
      url:
        type: "string"
        description: "Url to download file"


